---
- name: Router Durum Kontrolü
  hosts: cisco_routers
  gather_facts: no

  tasks:
    - name: Birden fazla komut calistir
      cisco.ios.ios_command:
        commands:
          - show ip int brief
          - show version | include uptime
          - show ip route
      register: router_output

    - name: Ciktilari ekrana bas
      debug:
        msg: "{{ item }}"
      loop: "{{ router_output.stdout_lines }}"
