[cisco_routers]
R1 ansible_host=192.168.129.131
R2 ansible_host=192.168.129.132

[cisco_routers:vars]
ansible_user=osman
ansible_password=cisco
ansible_connection=network_cli
ansible_network_os=cisco.ios.ios
ansible_become=yes
ansible_become_method=enable
ansible_become_password=cisco
